load("@tf_modules//:def.bzl", "terraform_module")

terraform_module(
    name = "multimodule",
    srcs = glob(["module1.tf"]),
)

terraform_module(
    name = "module2",
    srcs = glob(["module2.tf"]),
)
