load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "getopentofureleases_lib",
    srcs = ["main.go"],
    importpath = "tfmodules/tools/getopentofureleases",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "getopentofureleases",
    embed = [":getopentofureleases_lib"],
    visibility = ["//visibility:public"],
)
